spring:
  application:
    name: hello-service
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spri‌​ng.application.insta‌​nce_id:${random.valu‌​e}}
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 8

security:
  oauth2:
    resource:
      filter-order: 3
  basic:
    enabled: false
