spring:
  application:
    name: feign-client
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 8


security:
  oauth2:
    resource:
      filter-order: 3
  basic:
    enabled: false